### PR TITLE
merge-bufcompile-into-buf

### PR DESCRIPTION
**Pull request by nicksanford**
Revert edit to Makefile https://github.com/viamrobotics/slam/pull/135/files#diff-931a6e2149fb04d2ec1e4ae28596d823e5671314e365f0a590f6959d792caf80L11

### CODE REVIEW

**Comment by Otterverse** [comment]
Talked with John on this, found the issue. The new "buf" target now depends on two other targets, whereas previously it depended on one, then its own commands ran after that. Now it tries to run both at the same time, and the buf install doesn't finish before it tries to use it.

Basically "bufcompile: bufsetup" will fix it properly. Reverting it, as you are doing, is fine too.

**Comment by Otterverse** [comment]
Note that you can reproduce this in a normal environment with just:

```
rm grpc/bin/buf
make -j4 buf
```

**Review by Otterverse — APPROVED** [review]
Please see other comments about WHY this is happening, but this reversion is fine too.

**Comment by nicksanford** [comment]
> 

Thanks @JohnN193 & @Otterverse for helping diagnose. Yep, that makes sense. I'm going to merge this as is given that making buf depend on  bufcompile and bufcompile depend bufsetup ends up meaning that the buf command will do the exact same work as bufcompile, which defeats the purpose of having 2 commands. 

In the figure, I'll be sure to ensure that when defining targets that depend on more than one command don't care about the execution order of the dependent commands.

**Review by JohnN193 — APPROVED** [review]

**Pull request merged**
