### PR TITLE
[RSDK-1255] fix slam process exit handler

### PR DESCRIPTION
**Pull request by JohnN193**
Currently the slam algorithms fail to shut down when rdk attempts to close them. This PR attempts to update the exit handler to safely close out of the slam algorithms, based off information found in[ this PR](https://github.com/viamrobotics/goutils/pull/116). Will have a followup PR in rdk to clean up the integration test code

Note the changes make the clean shutdown occur only when running the slam servers with rdk. Running the binaries standalone/without managed process controlling them is not a behavior we need to support. 

https://viam.atlassian.net/browse/RSDK-1255

[RSDK-1255]: https://viam.atlassian.net/browse/RSDK-1255?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by JohnN193** [comment]
We now see the[ exit handler triggers ](https://github.com/viamrobotics/slam/actions/runs/3832288046/jobs/6522424589#step:12:370)from the slam repos, so we know managed process is closing out of the slam algorithms. We also no longer have the [unable to check exit status logs](https://github.com/viamrobotics/rdk/actions/runs/3687572584/jobs/6241321866#step:6:474) which we saw in the past, which indicated the issue was present

**Review by Otterverse — COMMENTED** [review]
So I'm glad that this is working now, but... is there any foreseeable situation where people run these binaries directly? If so, you should probably handle both SIGINT and SIGTERM (you can use the same handler) so that a human user can still use CTRL+C to exit the program gracefully, rather than having that be an uncaught signal and/or do nothing. If that's just NEVER going to be a concern though, then it's probably fine as is.

**Review by kkufieta — COMMENTED** [review]
I second James's concerns - I think no matter the likelihood of someone running the binaries directly, we should support clean shutdown for both situations.

**Review by Otterverse — APPROVED** [review]
LGTM!

**Review by kkufieta — APPROVED** [review]
LGTM

**Pull request merged**
